[free]
title = "[시리즈온] 이주의 무료영화"
url = "https://serieson.naver.com/movie/freeMovieList.nhn"
entrySelector = "ul.lst_freemovie li"
titleSelector = "strong.freemovie_title"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "span.freemovie_deadline"
waitUntil = "networkidle"

[sale]
title = "[시리즈온] 할인 영화관"
url = "https://serieson.naver.com/movie/categoryList.nhn?categoryCode=300003"
entrySelector = "ul.lst_thum.v1 li"
titleSelector = "a strong"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "strong.payment"
waitUntil = "networkidle"

[sale1000]
title = "[시리즈온] 천원관"
url = "https://serieson.naver.com/movie/categoryList.nhn?categoryCode=300007"
entrySelector = "ul.lst_thum.v1 li"
titleSelector = "a strong"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "p.price2.v2 em"
waitUntil = "networkidle"

[barrierfree]
title = "[시리즈온] 가치봄 영화관"
url = "https://serieson.naver.com/movie/categoryList.nhn?categoryCode=300009&tagCode=200000"
entrySelector = "ul.lst_thum.v1 li"
titleSelector = "a strong"
linkSelector = "a"
imageSelector = "a img"
contentSelector = "p.price2.v2"
waitUntil = "networkidle"

[event]
title = "[시리즈온] 이벤트"
url = "https://serieson.naver.com/movie/eventList.nhn"
entrySelector = "ul li.event:not(:first-child)"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"

[m_serieson_barrierfree]
title = "모바일 네이버 시리즈온 ─ 가치봄 영화관"
url = "https://m.serieson.naver.com/movie/categories/300009?tagCode=200000"
entrySelector = "ul li.lst"
titleSelector = "h5.tit"
linkSelector = "a"
contentSelector = "dl.price.pd_lft.cash_price"
imageSelector = "img.img4"
waitUntil = "networkidle"
